before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: dANXn2OfetzxTYpwfLXeC7wPtVHKMYcnS4wTT1S2cltLMMI8wX3FNkUksZJJJrzvIx3jrWg2zkWtFqChWttyecYrh/v/AOJFbIhxEYg86LYAC/SISwEBV6Q6NvCFpzKIM1rNFvxANSFePXIy1L2qO5c/YKYr0snlcAPpzOmQhEcdCoJuOW3QHPAzsPMg+aGTaC/JdYcOC0klnd6QQ2Wht21ysejCQrMArCEZyqmUKo35fEV24zqnx+cy/BmUBcBlboCbDquped2SMP43c8UfpByNm3YQBGle07hJ+22bzDYd1rk4wFpMTCBNOEG6urikZ+pOypAoyI8yydObUG0/V9eOKZ3l82OW+1ONt5gXzAn8ElOx/cpy+OI/tCwQd8AAjXpHNk0EZh7o553uny5MBWol2mq6AgrvDny8CvEBZt0AH6z9X6NNkSdhsCFETn5XqrwM6oRdX+trKuoqxSaLWeEhzaCZYE+tfwjg41NbHAgzKuOP1aZDXSjMXCr7Iwjx5Qi6tbV0uENioWQdTcyUi2p7NFWD1FfS2jybSFta1PLDark44NucFRe2DKBCg/S70zKN8dzXfEgnjDrtRP8iVBx+HKNwFA4IPdVMaw0GSnB6y69HTnMazKEaN9YIW6AeLwiL4R8FiaMjaxFWIh5gffiSOWAfLUlrWQaillrQZ84= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
